"""Add claim audit log for soc2

Revision ID: 2feb53d2cb75
Revises: 5d7a4f38d9b8
Create Date: 2026-04-25 06:54:59.627398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2feb53d2cb75'
down_revision: Union[str, Sequence[str], None] = '5d7a4f38d9b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_audit_log',
    sa.Column('id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('claim_id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('performed_by', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_audit_log_claim_id'), 'claim_audit_log', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_photos_claim_id'), 'claim_photos', ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_photos_claim_id'), table_name='claim_photos')
    op.drop_index(op.f('ix_claim_audit_log_claim_id'), table_name='claim_audit_log')
    op.drop_table('claim_audit_log')
    # ### end Alembic commands ###
